name: Node.js CICD  

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: Agent-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'   # adjust version as per your Jenkins setup

      - name: Lint Frontend # Install dependencies and lint frontend
        run: |
          cd client
          npm install
          npm run lint

      - name: Lint Backend # Install dependencies and lint backend
        run: |
          cd api
          npm install
          npm run lint

  gitleaks-scan:
    runs-on: Agent-1
    needs: compile

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: GitLeaks Setup
        uses: gitleaks/gitleaks-action@v2

      - name: GitLeaks-Scan
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1

  trivy-fs-scan:
    runs-on: Agent-1
    needs: gitleaks-scan

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
          
      
  

  
